export interface HeaderInput {
  sourceRelPath: string;
  commitSha: string;
  generatedAt: Date;
}

export function buildHeader({ sourceRelPath, commitSha, generatedAt }: HeaderInput): string {
  return [
    "# GENERATED BY synccenter — do not edit",
    `# source: ${sourceRelPath} @ commit ${commitSha}`,
    `# generated: ${generatedAt.toISOString()}`,
  ].join("\n");
}
