import { describe, it, expect } from "bun:test";
import { matchRuleset } from "../src/ruleset-match.ts";

describe("matchRuleset", () => {
  const known = {
    "base-binaries": [".DS_Store", "Thumbs.db", "*.tmp"],
    "dev-monorepo": [".DS_Store", "Thumbs.db", "*.tmp", "**/node_modules/", "**/.env", "!.env.example"],
  };

  it("returns the ruleset name when live ignores match exactly (any order)", () => {
    const live = ["Thumbs.db", "*.tmp", ".DS_Store"];
    expect(matchRuleset(live, known)).toBe("base-binaries");
  });

  it("returns the ruleset whose pattern set is a perfect match (ignoring comments and blanks)", () => {
    const live = [
      "# GENERATED BY synccenter — do not edit",
      "",
      ".DS_Store",
      "Thumbs.db",
      "*.tmp",
      "**/node_modules/",
      "**/.env",
      "!.env.example",
    ];
    expect(matchRuleset(live, known)).toBe("dev-monorepo");
  });

  it("returns null when no known ruleset matches", () => {
    const live = ["just-this.txt"];
    expect(matchRuleset(live, known)).toBeNull();
  });

  it("throws RULESET_AMBIGUOUS when live exactly matches two distinct rulesets (degenerate)", () => {
    const k = { a: ["x"], b: ["x"] };
    expect(() => matchRuleset(["x"], k)).toThrow(/RULESET_AMBIGUOUS/);
  });
});
