import type { SchedulePlan } from "./types.ts";

export function renderCrontab(plans: SchedulePlan[]): string {
  if (plans.length === 0) return "";
  const lines = [
    "# GENERATED BY synccenter — do not edit",
    "# SchedulePlan → crontab fragment",
    "",
  ];
  for (const p of plans) {
    lines.push(`# ${p.folder} → ${p.anchor}`);
    lines.push(`${p.cron} ${p.command}`);
  }
  return lines.join("\n") + "\n";
}
