import { describe, expect, it } from "bun:test";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { compile, CompileError, normalizePatterns } from "../src/index.ts";

const HERE = new URL(".", import.meta.url).pathname;
const RULES_DIR = join(HERE, "fixtures", "rules");
const IMPORTS_DIR = join(HERE, "fixtures", "imports");
const FIXED_DATE = new Date("2026-05-14T10:30:00.000Z");

function compileFixture(name: string, allowDivergent = false) {
  return compile(join(RULES_DIR, `${name}.yaml`), {
    rulesetsDir: RULES_DIR,
    importsDir: IMPORTS_DIR,
    commitSha: "abc1234",
    allowDivergent,
    now: FIXED_DATE,
  });
}

/**
 * Compile a one-off ruleset written to a REAL temp dir, never into
 * `fixtures/rules/`. Writing a throwaway .yaml next to the committed fixtures
 * and deleting it in `finally` leaves it behind whenever the process dies
 * between the two (SIGKILL, a crashing assertion), and the next run's fixture
 * glob then picks up a file git never tracked.
 */
function compileInTemp(name: string, yaml: string, allowDivergent = false) {
  const dir = mkdtempSync(join(tmpdir(), "synccenter-rules-"));
  try {
    const path = join(dir, `${name}.yaml`);
    writeFileSync(path, yaml);
    return compile(path, {
      rulesetsDir: dir,
      importsDir: IMPORTS_DIR,
      commitSha: "abc1234",
      allowDivergent,
      now: FIXED_DATE,
    });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

describe("compile()", () => {
  it("emits .stignore and rclone filter for a leaf ruleset", () => {
    const r = compileFixture("base-binaries");
    expect(r.warnings).toEqual([]);

    // Header
    expect(r.stignore).toContain("# GENERATED BY synccenter");
    expect(r.stignore).toContain("# source: base-binaries.yaml @ commit abc1234");
    expect(r.stignore).toContain("# generated: 2026-05-14T10:30:00.000Z");

    // Patterns preserved verbatim
    expect(r.stignore).toContain(".DS_Store");
    expect(r.stignore).toContain("Thumbs.db");
    expect(r.stignore).toContain("**/*.tmp");
    expect(r.stignore).toContain("**/*.swp");
  });

  it("reverses pattern order for rclone (first-match-wins) and appends + ** catch-all", () => {
    const r = compileFixture("base-binaries");
    const lines = r.rcloneFilter.trim().split("\n");
    // After the 3-line header + blank line:
    const body = lines.slice(4);
    expect(body[0]).toBe("- **/*.swp"); // last input pattern, first in rclone output
    expect(body[1]).toBe("- **/*.tmp");
    expect(body[2]).toBe("- Thumbs.db");
    expect(body[3]).toBe("- .DS_Store");
    expect(body[body.length - 1]).toBe("+ **");
  });

  it("emits .stignore reversed (first-match-wins): includes, then own patterns, then imports", () => {
    const r = compileFixture("dev-monorepo");
    const stLines = r.stignore.split("\n");
    const idxBase = stLines.indexOf(".DS_Store"); // from ruleset://base-binaries
    const idxNodeModules = stLines.indexOf("node_modules/"); // from github://Node
    const idxOwnEnv = stLines.indexOf("**/.env"); // from this ruleset
    const idxNegEnvExample = stLines.indexOf("!**/.env.example"); // includes:

    // Syncthing takes the FIRST matching pattern, so the resolution order is
    // reversed on emit — the negation must precede the exclude it carves out.
    expect(idxNegEnvExample).toBeGreaterThan(-1);
    expect(idxOwnEnv).toBeGreaterThan(idxNegEnvExample);
    expect(idxNodeModules).toBeGreaterThan(idxOwnEnv);
    expect(idxBase).toBeGreaterThan(idxNodeModules);

    // Strips comments and blank lines from imported gitignore files
    expect(r.stignore).not.toContain("# Logs");
    expect(r.stignore).not.toContain("# Dependencies");
  });

  it("translates includes (!) to '+ pattern' in rclone, ahead of '- pattern' equivalents", () => {
    const r = compileFixture("dev-monorepo");
    const idxNegEnvExample = r.rcloneFilter.indexOf("+ **/.env.example");
    const idxEnv = r.rcloneFilter.indexOf("- **/.env");
    expect(idxNegEnvExample).toBeGreaterThan(-1);
    expect(idxEnv).toBeGreaterThan(-1);
    // include comes earlier in the rclone output so first-match-wins keeps it.
    expect(idxNegEnvExample).toBeLessThan(idxEnv);
  });

  it("appends engine-specific extras and respects rclone catch-all override", () => {
    const r = compileFixture("with-overrides", /* allowDivergent */ true);
    expect(r.stignore).toContain("(?d)*.bak");

    const rcLines = r.rcloneFilter.trim().split("\n");
    // The override provided '- *' as catch-all, so no implicit '+ **' should be appended.
    expect(rcLines[rcLines.length - 1]).toBe("- *");
    expect(rcLines).toContain("+ *.important");
    expect(rcLines.filter((l) => l === "+ **").length).toBe(0);
  });

  it("flags engine divergence and refuses to compile without allowDivergent", () => {
    expect(() => compileFixture("with-divergent")).toThrow(CompileError);
    const r = compileFixture("with-divergent", true);
    expect(r.warnings.length).toBe(1);
    expect(r.warnings[0]).toContain("Syncthing-only syntax");
  });

  it("rejects a missing github cache with an actionable error", () => {
    expect(() =>
      compile(join(RULES_DIR, "dev-monorepo.yaml"), {
        rulesetsDir: RULES_DIR,
        importsDir: join(HERE, "fixtures", "nonexistent-cache"),
        commitSha: "abc1234",
        now: FIXED_DATE,
      }),
    ).toThrow(/import not cached locally/);
  });

  // Regression: a broad `includes:` negation used to be unconditionally the
  // highest-priority block, so `!/dev/**​/.github/**` re-included .github dirs
  // out of node_modules that `excludes:` had correctly removed — first-match-
  // wins meant the exclude never got a look. hard_excludes must beat it.
  it("emits hard_excludes ahead of includes in both artifacts", () => {
    const r = compileFixture("with-hard-excludes");

    for (const [engine, text, hard, inc] of [
      ["rclone", r.rcloneFilter, "- **/node_modules/**/.*", "+ /dev/**/.github/**"],
      ["stignore", r.stignore, "**/node_modules/**/.*", "!/dev/**/.github/**"],
    ] as const) {
      const lines = text.trim().split("\n");
      const hardAt = lines.indexOf(hard);
      const incAt = lines.indexOf(inc);
      expect(hardAt, `${engine}: hard exclude missing`).toBeGreaterThan(-1);
      expect(incAt, `${engine}: include missing`).toBeGreaterThan(-1);
      expect(hardAt, `${engine}: hard exclude must win first-match`).toBeLessThan(incAt);
    }
  });

  it("rejects a '!' in hard_excludes, which would invert it into a re-include", () => {
    expect(() =>
      compileInTemp("bad-hard-excludes", "name: bad-hard-excludes\nversion: 1\nhard_excludes:\n  - '!oops'\n"),
    ).toThrow(/hard_excludes\[\] entries must not start with '!'/);
  });

  // `emitStignore` cannot rewrite every class it knows Syncthing will reject:
  // a span crossing `]` or `\` has no literal-list form, and a very wide range
  // beside another token is never what a ruleset meant. Passing those through
  // is safe for rclone but still costs the ENTIRE .stignore on the Syncthing
  // side, so compile() must refuse rather than emit a file that silently turns
  // every ignore off.
  it("refuses to emit a bracket class Syncthing cannot parse and the emitter cannot fix", () => {
    expect(() =>
      // A-_ spans 0x41-0x5F, crossing both `]` and `\`, and is followed by a-z.
      compileInTemp("fatal-bracket", 'name: fatal-bracket\nversion: 1\nexcludes:\n  - "junk[A-_a-z]"\n'),
    ).toThrow(/discard the ENTIRE \.stignore/);
  });

  // Not overridable. Divergence is a trade-off an operator can accept knowingly;
  // an unparseable class is a guaranteed-broken artifact either way.
  it("refuses even with allowDivergent, unlike an engine-divergence warning", () => {
    expect(() =>
      compileInTemp("fatal-bracket", 'name: fatal-bracket\nversion: 1\nexcludes:\n  - "junk[A-_a-z]"\n', true),
    ).toThrow(CompileError);
  });

  // rclone accepts these, and rclone extras never reach .stignore, so the guard
  // must not fire on them — otherwise a legitimate rclone-only pattern becomes
  // uncompilable for no reason.
  it("ignores an unparseable class in an rclone-only override", () => {
    const r = compileInTemp(
      "rclone-only-bracket",
      'name: rclone-only-bracket\nversion: 1\nexcludes:\n  - "keep"\nengine_overrides:\n  rclone:\n    extra:\n      - "- junk[A-_a-z]"\n',
    );
    expect(r.rcloneFilter).toContain("junk[A-_a-z]");
  });
});

describe("normalizePatterns()", () => {
  it("strips comments, blanks, BOMs, and trailing whitespace", () => {
    const raw = "﻿# top comment\n\n*.log  \n!important.log\n  # indented comment is also dropped\n";
    expect(normalizePatterns(raw)).toEqual(["*.log", "!important.log"]);
  });

  it("normalizes backslashes to forward slashes (POSIX)", () => {
    expect(normalizePatterns("path\\to\\thing\n")).toEqual(["path/to/thing"]);
  });
});
