import { describe, expect, it } from "bun:test";
import { join } from "node:path";
import { compile, CompileError, normalizePatterns } from "../src/index.ts";

const HERE = new URL(".", import.meta.url).pathname;
const RULES_DIR = join(HERE, "fixtures", "rules");
const IMPORTS_DIR = join(HERE, "fixtures", "imports");
const FIXED_DATE = new Date("2026-05-14T10:30:00.000Z");

function compileFixture(name: string, allowDivergent = false) {
  return compile(join(RULES_DIR, `${name}.yaml`), {
    rulesetsDir: RULES_DIR,
    importsDir: IMPORTS_DIR,
    commitSha: "abc1234",
    allowDivergent,
    now: FIXED_DATE,
  });
}

describe("compile()", () => {
  it("emits .stignore and rclone filter for a leaf ruleset", () => {
    const r = compileFixture("base-binaries");
    expect(r.warnings).toEqual([]);

    // Header
    expect(r.stignore).toContain("# GENERATED BY synccenter");
    expect(r.stignore).toContain("# source: base-binaries.yaml @ commit abc1234");
    expect(r.stignore).toContain("# generated: 2026-05-14T10:30:00.000Z");

    // Patterns preserved verbatim
    expect(r.stignore).toContain(".DS_Store");
    expect(r.stignore).toContain("Thumbs.db");
    expect(r.stignore).toContain("**/*.tmp");
    expect(r.stignore).toContain("**/*.swp");
  });

  it("reverses pattern order for rclone (first-match-wins) and appends + ** catch-all", () => {
    const r = compileFixture("base-binaries");
    const lines = r.rcloneFilter.trim().split("\n");
    // After the 3-line header + blank line:
    const body = lines.slice(4);
    expect(body[0]).toBe("- **/*.swp"); // last input pattern, first in rclone output
    expect(body[1]).toBe("- **/*.tmp");
    expect(body[2]).toBe("- Thumbs.db");
    expect(body[3]).toBe("- .DS_Store");
    expect(body[body.length - 1]).toBe("+ **");
  });

  it("resolves ruleset:// + github:// imports in order, then own patterns, then includes", () => {
    const r = compileFixture("dev-monorepo");
    const stLines = r.stignore.split("\n");
    const idxBase = stLines.indexOf(".DS_Store"); // from ruleset://base-binaries
    const idxNodeModules = stLines.indexOf("node_modules/"); // from github://Node
    const idxOwnEnv = stLines.indexOf("**/.env"); // from this ruleset
    const idxNegEnvExample = stLines.indexOf("!**/.env.example"); // includes:

    expect(idxBase).toBeGreaterThan(-1);
    expect(idxNodeModules).toBeGreaterThan(idxBase);
    expect(idxOwnEnv).toBeGreaterThan(idxNodeModules);
    expect(idxNegEnvExample).toBeGreaterThan(idxOwnEnv);

    // Strips comments and blank lines from imported gitignore files
    expect(r.stignore).not.toContain("# Logs");
    expect(r.stignore).not.toContain("# Dependencies");
  });

  it("translates includes (!) to '+ pattern' in rclone, ahead of '- pattern' equivalents", () => {
    const r = compileFixture("dev-monorepo");
    const idxNegEnvExample = r.rcloneFilter.indexOf("+ **/.env.example");
    const idxEnv = r.rcloneFilter.indexOf("- **/.env");
    expect(idxNegEnvExample).toBeGreaterThan(-1);
    expect(idxEnv).toBeGreaterThan(-1);
    // include comes earlier in the rclone output so first-match-wins keeps it.
    expect(idxNegEnvExample).toBeLessThan(idxEnv);
  });

  it("appends engine-specific extras and respects rclone catch-all override", () => {
    const r = compileFixture("with-overrides", /* allowDivergent */ true);
    expect(r.stignore).toContain("(?d)*.bak");

    const rcLines = r.rcloneFilter.trim().split("\n");
    // The override provided '- *' as catch-all, so no implicit '+ **' should be appended.
    expect(rcLines[rcLines.length - 1]).toBe("- *");
    expect(rcLines).toContain("+ *.important");
    expect(rcLines.filter((l) => l === "+ **").length).toBe(0);
  });

  it("flags engine divergence and refuses to compile without allowDivergent", () => {
    expect(() => compileFixture("with-divergent")).toThrow(CompileError);
    const r = compileFixture("with-divergent", true);
    expect(r.warnings.length).toBe(1);
    expect(r.warnings[0]).toContain("Syncthing-only syntax");
  });

  it("rejects a missing github cache with an actionable error", () => {
    expect(() =>
      compile(join(RULES_DIR, "dev-monorepo.yaml"), {
        rulesetsDir: RULES_DIR,
        importsDir: join(HERE, "fixtures", "nonexistent-cache"),
        commitSha: "abc1234",
        now: FIXED_DATE,
      }),
    ).toThrow(/import not cached locally/);
  });
});

describe("normalizePatterns()", () => {
  it("strips comments, blanks, BOMs, and trailing whitespace", () => {
    const raw = "﻿# top comment\n\n*.log  \n!important.log\n  # indented comment is also dropped\n";
    expect(normalizePatterns(raw)).toEqual(["*.log", "!important.log"]);
  });

  it("normalizes backslashes to forward slashes (POSIX)", () => {
    expect(normalizePatterns("path\\to\\thing\n")).toEqual(["path/to/thing"]);
  });
});
