#!/usr/bin/env bash
# qnap-bootstrap.sh — one-shot Syncthing + rclone bring-up on a QNAP.
#
# Run as `admin` on the QNAP (admin already has sudo equivalents on QTS).
# Idempotent — safe to re-run; existing containers are recreated only if the
# compose file changes.
#
# What it does:
#   1. Creates /share/Container/synccenter/{syncthing,state,rclone-config} and /share/Sync
#   2. Writes a minimal docker-compose.yml for syncthing + rclone-rcd
#   3. docker compose up -d
#   4. Persists fs.inotify.max_user_watches=524288 via /etc/config/autorun.sh
#      (QTS persists /etc/config across firmware updates — it's on the DOM partition)
#   5. Prints the Syncthing device ID + API key so the operator can copy them

set -euo pipefail

# Container Station ships docker on a non-default path.
export PATH="/share/CACHEDEV1_DATA/.qpkg/container-station/usr/bin:${PATH}"

CONTAINER_ROOT="/share/Container/synccenter"
COMPOSE_FILE="${CONTAINER_ROOT}/docker-compose.yml"
SYNCTHING_CONFIG_DIR="${CONTAINER_ROOT}/syncthing"
STATE_DIR="${CONTAINER_ROOT}/state"
RCLONE_CONFIG_DIR="${CONTAINER_ROOT}/rclone-config"
SYNC_ROOT="/share/Sync"
AUTORUN="/etc/config/autorun.sh"

# Defaults — override via env.
RCLONE_USER="${SC_RCLONE_USER:-synccenter}"
RCLONE_PASS="${SC_RCLONE_PASS:-$(head -c 24 /dev/urandom | base64 | tr -d '/+=' )}"

command -v docker >/dev/null || {
  echo "docker not on PATH even after adding Container Station's bin dir." >&2
  echo "Is Container Station installed? Try: qpkg_service start container-station" >&2
  exit 1
}
docker compose version >/dev/null 2>&1 || { echo "docker compose plugin missing"; exit 1; }

echo "==> creating dirs"
mkdir -p "${SYNCTHING_CONFIG_DIR}" "${STATE_DIR}" "${RCLONE_CONFIG_DIR}" "${SYNC_ROOT}"
chown -R 1000:1000 "${SYNCTHING_CONFIG_DIR}" "${SYNC_ROOT}"

echo "==> writing docker-compose.yml at ${COMPOSE_FILE}"
cat > "${COMPOSE_FILE}" <<EOF
# Generated by qnap-bootstrap.sh — re-run the script to refresh.

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: America/Toronto
    volumes:
      - ${SYNCTHING_CONFIG_DIR}:/config
      - ${SYNC_ROOT}:/Sync
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    # net.core.{rmem,wmem}_max sysctls (LSIO's perf recommendation) are
    # rejected by QTS's container namespacing — host-level sysctl set in
    # /etc/config/autorun.sh instead.

  rclone-rcd:
    image: rclone/rclone:latest
    container_name: rclone-rcd
    restart: unless-stopped
    command:
      - rcd
      - --rc-addr=0.0.0.0:5572
      - --rc-user=${RCLONE_USER}
      - --rc-pass=${RCLONE_PASS}
      - --config=/config/rclone.conf
    volumes:
      - ${RCLONE_CONFIG_DIR}:/config
      - ${SYNC_ROOT}:/Sync
    ports:
      - "127.0.0.1:5572:5572"
EOF

echo "==> docker compose up -d"
docker compose -f "${COMPOSE_FILE}" up -d

echo "==> raising inotify watch limit"
sysctl -w fs.inotify.max_user_watches=524288 >/dev/null

# Persist across reboots. /etc/config/ lives on the DOM partition and
# survives firmware updates. The operator must also enable autorun in
# QTS → Control Panel → Hardware → General → "Run user defined processes
# during startup of network services" — without that toggle the file is
# present but never invoked.
LINE="sysctl -w fs.inotify.max_user_watches=524288"
if [[ -f "${AUTORUN}" ]] && grep -qF "${LINE}" "${AUTORUN}"; then
  echo "    (inotify line already in ${AUTORUN})"
else
  if [[ ! -f "${AUTORUN}" ]]; then
    printf '#!/bin/sh\n# QNAP user autorun — invoked at boot when enabled in QTS Control Panel.\n' > "${AUTORUN}"
  fi
  echo "${LINE}" >> "${AUTORUN}"
  chmod +x "${AUTORUN}"
  echo "    appended to ${AUTORUN}"
  echo "    NOTE: enable autorun in QTS Control Panel → Hardware → General"
  echo "          → 'Run user defined processes during startup of network services'"
fi

echo
echo "==> waiting for Syncthing to write its config (~5s)…"
sleep 6

# Extract device ID + API key from the freshly-written config.xml.
CONFIG_XML="${SYNCTHING_CONFIG_DIR}/config.xml"
if [[ ! -f "${CONFIG_XML}" ]]; then
  echo "  config.xml not found at ${CONFIG_XML} — container may still be initializing." >&2
  echo "  Re-run: 'docker logs syncthing' to inspect." >&2
  exit 1
fi

API_KEY=$(sed -nE 's|.*<apikey>([^<]+)</apikey>.*|\1|p' "${CONFIG_XML}" | head -1)
DEVICE_ID=$(curl -s http://127.0.0.1:8384/rest/system/status -H "X-API-Key: ${API_KEY}" | grep -oE '"myID":"[^"]+"' | sed 's/"myID":"//; s/"//')

cat <<EOF

============================================================
QNAP bring-up complete.
------------------------------------------------------------
Syncthing device ID:  ${DEVICE_ID:-<not yet ready — re-run after 30s>}
Syncthing API key:    ${API_KEY:-<not found>}
rclone user / pass:   ${RCLONE_USER} / ${RCLONE_PASS}
rclone rcd:           http://127.0.0.1:5572  (localhost-only)
Syncthing GUI:        http://<qnap-ip>:8384

Save the device ID + API key + rclone password — Phase 1 Step 6
seeds them into sops-encrypted secrets in synccenter-config.

The compose file lives at ${COMPOSE_FILE}.
Re-run this script any time to refresh it.
============================================================
EOF
