#!/usr/bin/env bash
# qnap-bootstrap.sh — one-shot Syncthing + rclone bring-up on a QNAP.
#
# Run AS ROOT on the QNAP (admin user has sudo on QTS). Idempotent — safe to
# re-run; existing containers are left alone if their config matches.
#
# What it does:
#   1. Creates /share/Container/synccenter/{syncthing,state,rclone-config} and /share/Sync
#   2. Writes a minimal docker-compose.yml for syncthing + rclone-rcd
#   3. docker compose up -d
#   4. Persists fs.inotify.max_user_watches=524288 via /etc/init.d/autorun.sh
#   5. Prints the Syncthing device ID + API key so the operator can copy them

set -euo pipefail

CONTAINER_ROOT="/share/Container/synccenter"
COMPOSE_FILE="${CONTAINER_ROOT}/docker-compose.yml"
SYNCTHING_CONFIG_DIR="${CONTAINER_ROOT}/syncthing"
STATE_DIR="${CONTAINER_ROOT}/state"
RCLONE_CONFIG_DIR="${CONTAINER_ROOT}/rclone-config"
SYNC_ROOT="/share/Sync"

# Defaults — override via env.
RCLONE_USER="${SC_RCLONE_USER:-synccenter}"
RCLONE_PASS="${SC_RCLONE_PASS:-$(head -c 24 /dev/urandom | base64 | tr -d '/+=' )}"

if [[ $EUID -ne 0 ]]; then
  echo "must run as root (sudo bash $0)" >&2
  exit 1
fi

command -v docker >/dev/null || { echo "docker not installed — install Container Station QPKG"; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "docker compose plugin missing"; exit 1; }

echo "==> creating dirs"
mkdir -p "${SYNCTHING_CONFIG_DIR}" "${STATE_DIR}" "${RCLONE_CONFIG_DIR}" "${SYNC_ROOT}"
chown -R 1000:1000 "${SYNCTHING_CONFIG_DIR}" "${SYNC_ROOT}"

echo "==> writing docker-compose.yml at ${COMPOSE_FILE}"
cat > "${COMPOSE_FILE}" <<EOF
# Generated by qnap-bootstrap.sh — re-run the script to refresh.

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: America/Toronto
    volumes:
      - ${SYNCTHING_CONFIG_DIR}:/config
      - ${SYNC_ROOT}:/Sync
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    sysctls:
      net.core.rmem_max: "7500000"
      net.core.wmem_max: "7500000"

  rclone-rcd:
    image: rclone/rclone:latest
    container_name: rclone-rcd
    restart: unless-stopped
    command:
      - rcd
      - --rc-addr=0.0.0.0:5572
      - --rc-user=${RCLONE_USER}
      - --rc-pass=${RCLONE_PASS}
      - --config=/config/rclone.conf
    volumes:
      - ${RCLONE_CONFIG_DIR}:/config
      - ${SYNC_ROOT}:/Sync
    ports:
      - "127.0.0.1:5572:5572"
EOF

echo "==> docker compose up -d"
docker compose -f "${COMPOSE_FILE}" up -d

echo "==> raising inotify watch limit"
sysctl -w fs.inotify.max_user_watches=524288 >/dev/null

# Persist across reboots. QTS replays /etc/config/qpkg.conf scripts and
# /etc/init.d/autorun.sh; we append to autorun.sh because it survives firmware
# updates if the operator follows the standard QNAP pattern of storing it on
# /share. We refuse to double-append.
AUTORUN="/etc/init.d/autorun.sh"
LINE="sysctl -w fs.inotify.max_user_watches=524288"
if [[ -f "${AUTORUN}" ]] && grep -qF "${LINE}" "${AUTORUN}"; then
  echo "    (inotify line already in ${AUTORUN})"
else
  echo "${LINE}" >> "${AUTORUN}"
  chmod +x "${AUTORUN}"
  echo "    appended to ${AUTORUN}"
fi

echo
echo "==> waiting for Syncthing to write its config (~5s)…"
sleep 6

# Extract device ID + API key from the freshly-written config.xml.
CONFIG_XML="${SYNCTHING_CONFIG_DIR}/config.xml"
if [[ ! -f "${CONFIG_XML}" ]]; then
  echo "  config.xml not found at ${CONFIG_XML} — container may still be initializing." >&2
  echo "  Re-run: 'docker logs syncthing' to inspect." >&2
  exit 1
fi

API_KEY=$(sed -nE 's|.*<apikey>([^<]+)</apikey>.*|\1|p' "${CONFIG_XML}" | head -1)
DEVICE_ID=$(curl -s http://127.0.0.1:8384/rest/system/status -H "X-API-Key: ${API_KEY}" | grep -oE '"myID":"[^"]+"' | sed 's/"myID":"//; s/"//')

cat <<EOF

============================================================
QNAP bring-up complete.
------------------------------------------------------------
Syncthing device ID:  ${DEVICE_ID:-<not yet ready — re-run after 30s>}
Syncthing API key:    ${API_KEY:-<not found>}
rclone user / pass:   ${RCLONE_USER} / ${RCLONE_PASS}
rclone rcd:           http://127.0.0.1:5572  (localhost-only)
Syncthing GUI:        http://<qnap-ip>:8384

Save the device ID + API key + rclone password — Phase 1 Step 6
seeds them into sops-encrypted secrets in synccenter-config.

The compose file lives at ${COMPOSE_FILE}.
Re-run this script any time to refresh it.
============================================================
EOF
