#!/usr/bin/env bash
# render-rclone-conf.sh — emit a rclone.conf to stdout with OAuth tokens
# decrypted from synccenter-config/secrets/.
#
# Remotes:
#   gdrive              ericbaruch@gmail.com, rooted at the Drive "SyncCenter" folder
#   gdrive-arik         same account/token, rooted at /My Drive (folders/arik.yaml)
#   gdrive-baruchriollc baruchriollc@gmail.com /My Drive (folders/baruchrio.yaml);
#                       emitted only once its sealed token exists — run
#                       `rclone authorize "drive"` signed in to that account and
#                       seal the JSON into secrets/gdrive-baruchriollc-oauth-token.enc.json.
#
# Use it to seed:
#   - ~/.config/rclone/rclone.conf            (Mac host)
#   - /share/Container/synccenter/rclone-config/rclone.conf  (QNAP rclone-rcd container)
#
# Examples:
#   scripts/render-rclone-conf.sh > ~/.config/rclone/rclone.conf
#   scripts/render-rclone-conf.sh | ssh admin@192.168.1.10 \
#     'cat > /share/Container/synccenter/rclone-config/rclone.conf'

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/.." && pwd)"
CONFIG_REPO="${SC_CONFIG_DIR:-${REPO_ROOT}/../synccenter-config}"

# Path inside My Drive: the "SyncCenter" folder created at root.
ROOT_FOLDER_ID="${SC_GDRIVE_ROOT_ID:-1TOL6-uIHZs7WiNiFOZlYjUCKNcBmRs9J}"

TOKEN_FILE="${CONFIG_REPO}/secrets/gdrive-oauth-token.enc.json"
[[ -f "${TOKEN_FILE}" ]] || { echo "missing sealed token at ${TOKEN_FILE}" >&2; exit 1; }
command -v sops >/dev/null || { echo "sops not installed" >&2; exit 1; }

# Compact the decrypted JSON to a single line — rclone.conf parses values
# as one line and chokes on the pretty-printed form sops emits.
TOKEN_JSON="$(sops -d "${TOKEN_FILE}" | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin), separators=(",", ":")))')"

cat <<EOF
# Generated by render-rclone-conf.sh — do not hand-edit.
# To rotate an OAuth token, run \`rclone authorize "drive"\` and re-seal it
# into the matching secrets/*.enc.json.

[gdrive]
type = drive
scope = drive
root_folder_id = ${ROOT_FOLDER_ID}
token = ${TOKEN_JSON}

# Same account, but rooted at /My Drive — the HBS3 "Arik" job destination.
[gdrive-arik]
type = drive
scope = drive
token = ${TOKEN_JSON}
EOF

BRIO_TOKEN_FILE="${CONFIG_REPO}/secrets/gdrive-baruchriollc-oauth-token.enc.json"
if [[ -f "${BRIO_TOKEN_FILE}" ]]; then
  BRIO_TOKEN_JSON="$(sops -d "${BRIO_TOKEN_FILE}" | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin), separators=(",", ":")))')"
  cat <<EOF

# baruchriollc@gmail.com /My Drive — the HBS3 "BaruchRioLLC Sync" destination.
[gdrive-baruchriollc]
type = drive
scope = drive
token = ${BRIO_TOKEN_JSON}
EOF
else
  echo "note: ${BRIO_TOKEN_FILE} not found — [gdrive-baruchriollc] omitted" >&2
fi
