#!/usr/bin/env bash
# render-rclone-conf.sh — emit a rclone.conf to stdout with the gdrive
# OAuth token decrypted from synccenter-config/secrets/gdrive-oauth-token.enc.json.
#
# Use it to seed:
#   - ~/.config/rclone/rclone.conf            (Mac host)
#   - /share/Container/synccenter/rclone-config/rclone.conf  (QNAP rclone-rcd container)
#
# Examples:
#   scripts/render-rclone-conf.sh > ~/.config/rclone/rclone.conf
#   scripts/render-rclone-conf.sh | ssh admin@192.168.1.10 \
#     'cat > /share/Container/synccenter/rclone-config/rclone.conf'

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/.." && pwd)"
CONFIG_REPO="${SC_CONFIG_DIR:-${REPO_ROOT}/../synccenter-config}"

# Path inside My Drive: the "SyncCenter" folder created at root.
ROOT_FOLDER_ID="${SC_GDRIVE_ROOT_ID:-1TOL6-uIHZs7WiNiFOZlYjUCKNcBmRs9J}"

TOKEN_FILE="${CONFIG_REPO}/secrets/gdrive-oauth-token.enc.json"
[[ -f "${TOKEN_FILE}" ]] || { echo "missing sealed token at ${TOKEN_FILE}" >&2; exit 1; }
command -v sops >/dev/null || { echo "sops not installed" >&2; exit 1; }

# Compact the decrypted JSON to a single line — rclone.conf parses values
# as one line and chokes on the pretty-printed form sops emits.
TOKEN_JSON="$(sops -d "${TOKEN_FILE}" | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin), separators=(",", ":")))')"

cat <<EOF
# Generated by render-rclone-conf.sh — do not hand-edit.
# To rotate the OAuth token, run \`rclone authorize "drive"\` and re-seal it
# into ${TOKEN_FILE#${REPO_ROOT}/}.

[gdrive]
type = drive
scope = drive
root_folder_id = ${ROOT_FOLDER_ID}
token = ${TOKEN_JSON}
EOF
